name: Test Plone Training documentation

on: [push, pull_request]

jobs:
  test:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0

      - name: Install dependencies
        run: |
          sudo snap install --edge vale

      - name: Run tests with make test (includes clean and linkcheckbroken)
        run: make test

      - name: Run Vale
        run: make vale VALEOPTS="--no-exit --minAlertLevel='warning'"
